default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: banking_app_development

test:
  <<: *default
  database: banking_app_test

production:
  <<: *default
  database: banking_app_production
  username: banking_app
  password: <%= ENV["BANKING_APP_DATABASE_PASSWORD"] %>
